export const metricsDefinitions = {
  sessionMetrics: [
    {
      name: "Daily Sessions",
      explanation: "Total number of daily active sessions",
      visualization: "Line chart",
      tier: "Free",
      version: "V1",
    },
    {
      name: "Daily Active Users (DAU)",
      explanation:
        "Number of unique users who interacted with the platform in the last 24 hours",
      visualization: "Line chart",
      tier: "Pro",
      version: "V2",
    },
    {
      name: "Weekly Active Users (WAU)",
      explanation:
        "Number of unique users who interacted with the platform in the last 7 days",
      visualization: "Line chart",
      tier: "Pro",
      version: "V2",
    },
    {
      name: "Monthly Active Users (MAU)",
      explanation:
        "Number of unique users who interacted with the platform in the last 30 days",
      visualization: "Line chart",
      tier: "Free",
      version: "V2",
    },
    {
      name: "Country Distribution",
      explanation: "Geographic distribution of user sessions by country",
      visualization: "Pie chart",
      tier: "Free",
      version: "V2",
    },
    {
      name: "Platform Distribution",
      explanation:
        "Breakdown of operating systems (Linux, Windows, iOS, macOS, Android) used to access your DApp",
      visualization: "Pie chart",
      tier: "Free",
      version: "V2",
    },
    {
      name: "Connection Channel Distribution",
      explanation: "Breakdown of connection types (Wallet, Social, Email)",
      visualization: "Pie chart",
      tier: "Pro",
      version: "V1",
    },
    {
      name: "Social Connection Types",
      explanation:
        "Distribution of social login providers (Google, Facebook, X)",
      visualization: "Donut chart",
      tier: "Pro",
      version: "V2",
    },
    {
      name: "Connection Success Rate by Channel",
      explanation:
        "Success rate for each connection method (Wallet, Social, Email)",
      visualization: "Bar chart",
      tier: "Pro",
      version: "V3",
    },
    {
      name: "Connection Method Distribution",
      explanation: "Breakdown of connection types (QR, mobile, extension)",
      visualization: "Pie chart",
      tier: "Free",
      version: "V1",
    },
    {
      name: "Connection Success Rate",
      explanation: "Percentage of successful connections by method",
      visualization: "Bar chart",
      tier: "Free",
      version: "V3",
    },
    {
      name: "Time to Connect",
      explanation: "Average seconds to complete connection",
      visualization: "Bar chart",
      tier: "Free",
      version: "V3",
    },
    {
      name: "Connection Drop-off Points",
      explanation: "Where users abandon the connection flow",
      visualization: "Funnel chart",
      tier: "Pro",
      version: "V3",
    },
  ],
  userBehavior: [
    {
      name: "Growth Accounting",
      explanation:
        "Weekly breakdown of user base changes (new, returning, resurrecting, dormant)",
      visualization: "Stacked bar chart",
      tier: "Pro",
      version: "V2",
    },
    {
      name: "Feature Usage",
      explanation: "Count of different actions (sign, send, etc.)",
      visualization: "Horizontal bar chart",
      tier: "Pro",
      version: "V2",
    },
    {
      name: "Time Spent",
      explanation: "Average minutes users spend per session",
      visualization: "Area chart",
      tier: "Pro",
      version: "V2",
    },
    {
      name: "Return Rate Analysis",
      explanation: "Users who reconnect within 24h, 7d, 30d",
      visualization: "Multi-series bar chart",
      tier: "Pro",
      version: "V2",
    },
    {
      name: "Dwell Time Between Actions",
      explanation: "Time between connection and first transaction",
      visualization: "Histogram",
      tier: "Pro",
      version: "V2",
    },
    {
      name: "User Segments",
      explanation: "Analysis of user types based on behavior patterns",
      visualization: "Donut chart with drill-down",
      tier: "Pro",
      version: "V2",
    },
  ],
  chainMetrics: [
    {
      name: "Chain Usage Distribution",
      explanation: "Percentage breakdown of chain activity",
      visualization: "Pie chart",
      tier: "Free",
      version: "V1",
    },
    {
      name: "RPC Request Success Rate",
      explanation: "Reliability of node connections by chain",
      visualization: "Heatmap",
      tier: "Pro",
      version: "V2",
    },
  ],
  technicalPerformance: [
    {
      name: "Error Distribution Analysis",
      explanation: "Types and frequency of errors",
      visualization: "Treemap",
      tier: "Pro",
      version: "V2",
    },
    {
      name: "Method Popularity",
      explanation: "Most frequently called smart contract methods",
      visualization: "Horizontal bar chart",
      tier: "Pro",
      version: "V1",
    },
    {
      name: "Wallet Compatibility Matrix",
      explanation: "Success rates by wallet/chain combinations",
      visualization: "Grid heatmap",
      tier: "Pro",
      version: "V2",
    },
  ],
  advancedAnalytics: [
    {
      name: "Transaction Value Distribution",
      explanation: "Range of transaction values with percentiles",
      visualization: "Box and whisker plot",
      tier: "Pro",
      version: "V2",
    },
    {
      name: "Gas Cost Impact Analysis",
      explanation: "Correlation: abandonment vs. gas prices",
      visualization: "Scatter plot with trend line",
      tier: "Pro",
      version: "V2",
    },
    {
      name: "Cohort Retention Analysis",
      explanation: "User retention over time by cohort",
      visualization: "Retention grid",
      tier: "Pro",
      version: "V2",
    },
    {
      name: "Predictive Usage Forecasting",
      explanation: "Projected platform usage",
      visualization: "Line chart with forecast zone",
      tier: "Pro",
      version: "V2",
    },
  ],
  swapMetrics: [
    {
      name: "Total Swaps",
      explanation: "Total number of swaps performed through WalletConnect",
      visualization: "Line chart with time series",
      tier: "Free",
      version: "V3",
    },
    {
      name: "Total Swaps Volume",
      explanation: "Total volume of swaps in USD",
      visualization: "Area chart",
      tier: "Free",
      version: "V3",
    },
    {
      name: "Trading Pairs",
      explanation: "Most popular token pairs for swaps",
      visualization: "Bar chart",
      tier: "Pro",
      version: "V3",
    },
    {
      name: "Swaps by Geography",
      explanation: "Distribution of swaps by geographic region",
      visualization: "World map heatmap",
      tier: "Pro",
      version: "V3",
    },
    {
      name: "Session to Swaps Ratio",
      explanation: "Conversion rate from sessions to completed swaps",
      visualization: "Line chart with ratio trend",
      tier: "Pro",
      version: "V3",
    },
  ],
  competitionMetrics: [
    {
      name: "Category Time Share",
      explanation:
        "Percentage of total time users spend in each Web3 category (DeFi, NFT, etc.)",
      visualization: "Grid with trend indicators",
      tier: "Pro",
      version: "V3",
    },
    {
      name: "Peak Usage Hours",
      explanation: "Most active hours for each category in UTC time",
      visualization: "Time badges",
      tier: "Pro",
      version: "V3",
    },
    {
      name: "App Time Distribution",
      explanation:
        "Breakdown of time spent in different apps within each category",
      visualization: "Pie chart per category",
      tier: "Pro",
      version: "V3",
    },
    {
      name: "Regional User Overlap",
      explanation:
        "Percentage of users that overlap between your app and competitors by region",
      visualization: "Progress bars by region",
      tier: "Pro",
      version: "V3",
    },
    {
      name: "Average Session Duration",
      explanation: "Average time users spend per session in each app",
      visualization: "Comparison metrics",
      tier: "Pro",
      version: "V3",
    },
    {
      name: "Weekly Engagement",
      explanation: "Average number of sessions per week for each app",
      visualization: "Comparison metrics",
      tier: "Pro",
      version: "V3",
    },
  ],
};
